# Introduction to NIMBLE

1) Practice with BUGS code. Do one of the following:

   - Write BUGS code for a normal random effects model with 6 groups and 10 observations in each group. 
   - Write the code for another model of your choice. 
   - Examine the BUGS code for one of the BUGS examples; see ```system.file('classic-bugs', package = "nimble")``` for the location of the examples on your machine, or look in [https://github.com/nimble-dev/nimble/tree/devel/packages/nimble/inst/classic-bugs/vol1](https://github.com/nimble-dev/nimble/tree/devel/packages/nimble/inst/classic-bugs/vol1).

2) Take your model from above, or the code from one of the BUGS examples and fit a basic MCMC.

# More MCMC

1) With the pump model, compare the MCMC performance of using univariate slice samplers on $\alpha$ and $\beta$ to the default samplers and to the blocked Metropolis sampler for ${\alpha, \beta}$ for longer MCMC runs. 

2) Try out other possible sampling schemes. 

3) Suppose you wanted to consider the predictive distribution for a new pump. 
    - Create a new version of the model that allows for this.  
    - Set the data for the new model such that the new pump's number of failures is missing and not treated as a data node.
    - Set up an MCMC for the new model. What kind of sampling should happen for the new pump failures? 

# More on BUGS models

1) Change the prior for the pump model or the model you experimented with to use an alternative parameterization. Run MCMCs under the old and new parameterization and see if the results seem to change. 

2) Write the Pareto distribution as a user-defined distribution.

3) Write an "IID normal" distribution that can be used for a vector of $n$ normally distributed random variables, $y_i \sim N(\mu, \sigma)$. Compare the speed of an MCMC based on using a for loop and *dnorm* in BUGS code to that based on using the user-defined distribution. When using the standard specification, make sure the MCMC does not use conjugate (Gibbs) sampling so results are comparable (you can set `useConjugacy=FALSE` in *configureMCMC()*). This makes for an apples-to-apples comparison since our MCMC system won't know how to use your IID normal distribution for conjugate updates. 


# Programming in NIMBLE

1) Using the pump model or the model you experimented with, set the hyperparameters (the variance components) for the model and simulate the random effects/latent process values. Now fix the data nodes as 'data'. See what happens if you try to use *simulate()* on the data nodes. 

2) Using the same model, calculate the full density of the model. Next calculate just the log-likelihood. Play around with changing values in the model and recalculating the density values.

3) Again using the same model, determine the dependents of the hyperparameters of the model. Now determine only the stochastic dependents. Finally, determine which are the data nodes. 

4) Take NIMBLE's random walk sampler and modify it to use a gamma distribution with mean equal to the current parameter value. Make sure to account for the ratio of the forward and backward proposal densities. 


