#! /usr/bin/Rscript
# usage:
# ./make_slides overview
# ./make_slides build_model
# etc.

library(knitr)
library(rmarkdown)

module <- commandArgs(trailingOnly = TRUE)
source <- paste(module, ".Rmd", sep = "")

if (file.exists(source)){
    knit(source, envir = new.env())
    system(paste("pandoc -s --webtex -t slidy ", paste(module, ".md", sep = ""), " -o ", paste(module, "_slides.html", sep = ""), " --self-contained"))
    render(source, envir = new.env()) # for style that can hide code chunks dynamically
    # knit2html(source, envir = new.env())
} else {
    cat("Error: ", source, " does not exist.\n")
}
